'use strict';
const $ = s => document.querySelector(s);
const fmt = v => typeof v === 'number' ? v.toLocaleString('es-BO', {maximumFractionDigits: 3}) : String(v ?? '');
const labels = {regresion:'Regresión', clasificacion:'Clasificación', observacional:'Telco · descriptiva', demo:'Demo A/B · datos simulados'};
let config, selected, currentJob=null, busy=false, paramsReady=false, paramsVersion=0, offset=0, totalFiltered=0, poll=null;
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function error(e){$('#error').textContent=e.message||String(e);$('#error').hidden=false;}
async function api(url,body){const response=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':config.token},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(data.error||'No se pudo completar la solicitud.');return data;}
function table(container,rows,columns){const host=$(container);host.replaceChildren();if(!rows.length){host.append(node('p','No hay registros con estos filtros.','inset small'));return;}const keys=columns||Object.keys(rows[0]),t=node('table'),head=node('thead'),hr=node('tr');keys.forEach(k=>hr.append(node('th',k)));head.append(hr);t.append(head);const body=node('tbody');rows.forEach(row=>{const tr=node('tr');keys.forEach(k=>{const cell=node('td');const val=row[k];if(k==='fuente_url' && String(val).startsWith('https://www.cndc.bo/')){const link=node('a','Ver fuente ↗');link.href=val;link.target='_blank';link.rel='noopener noreferrer';cell.append(link);}else{cell.textContent=fmt(val);if(typeof val==='number')cell.className='number';}tr.append(cell);});body.append(tr);});t.append(body);host.append(t);}
function switchTab(name){document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==name);document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);if(b.dataset.tab===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
async function dataset(initial=false){try{
 const q=new URLSearchParams({offset,limit:30,contrato:$('#contract-filter').value,churn:$('#churn-filter').value,cliente:$('#customer-filter').value});
 const d=await api('/api/dataset?'+q);totalFiltered=d.filtrados;table('#data-table',d.filas,d.columnas);
 $('#page-info').textContent=d.filtrados?`${fmt(offset+1)}–${fmt(Math.min(offset+30,d.filtrados))} de ${fmt(d.filtrados)} registros`:'0 registros';
 $('#prev').disabled=offset===0;$('#next').disabled=offset+30>=d.filtrados;
 if(initial){$('#stats').replaceChildren();for(const [label,value,note] of [['Clientes',fmt(d.total),'Una fila por cliente'],['Columnas',d.columnas_total,'Texto, números y categorías'],['Abandonaron',fmt(d.abandonos),`${(100*d.abandonos/d.total).toFixed(1)}% del dataset`],['Temas disponibles','11','Regresión, clasificación y comparación']]){const s=node('div',undefined,'stat');s.append(node('span',label),node('strong',value),node('small',note));$('#stats').append(s);}
 d.contratos.forEach(n=>{const opt=node('option',n);opt.value=n;$('#contract-filter').append(opt);});
 table('#dictionary',d.diccionario);table('#numeric-stats',d.estadisticas);table('#dataset-notes',d.ficha);
 $('#quality').textContent=`${d.duplicados} identificadores duplicados; ${d.vacios} TotalCharges vacíos. Se imputan solo dentro del entrenamiento. Dataset de ejemplo de IBM; no acredita una empresa boliviana. No contiene fechas ni un experimento A/B.`;}
 }catch(e){error(e);}}
$('#filters').addEventListener('submit',e=>{e.preventDefault();$('#error').hidden=true;offset=0;dataset();});
$('#reset-filter').addEventListener('click',()=>{$('#filters').reset();offset=0;$('#error').hidden=true;dataset();});
$('#prev').addEventListener('click',()=>{offset=Math.max(0,offset-30);dataset();});$('#next').addEventListener('click',()=>{if(offset+30<totalFiltered){offset+=30;dataset();}});

function buildModels(){for(const m of config.modelos){const card=node('article',undefined,'model-card');card.dataset.model=m.id;card.append(node('span',m.id.padStart(2,'0'),'model-num'),node('h3',m.nombre),node('p',m.descripcion),node('span',m.tareas.map(t=>labels[t]).join(' · '),'model-tasks'));const b=node('button','Abrir modelo →','button ghost');b.setAttribute('aria-label',`Abrir ${m.id}. ${m.nombre}`);b.addEventListener('click',()=>selectModel(m));card.append(b);$('#model-grid').append(card);}}
function selectModel(m){selected=m;$('#model-detail').hidden=false;$('#model-number').textContent='MODELO '+m.id.padStart(2,'0');$('#model-title').textContent=m.nombre;$('#model-description').textContent=m.descripcion;$('#task').replaceChildren();for(const t of m.tareas){const o=node('option',labels[t]);o.value=t;$('#task').append(o);}document.querySelectorAll('.model-card').forEach(c=>c.classList.toggle('selected',c.dataset.model===m.id));loadParams();$('#model-detail').scrollIntoView({behavior:'smooth',block:'start'});}
function runState(){$('#run').disabled=busy||!paramsReady;$('#run').textContent=busy?'Hay una ejecución en curso':'Ejecutar modelo';}
async function loadParams(){const version=++paramsVersion;paramsReady=false;runState();$('#params-summary').replaceChildren(node('p','Consultando configuración del código…','small'));$('#params-code').textContent='Cargando…';const task=$('#task').value;$('#task-note').textContent=task==='demo'?'Este modo utiliza 2.000 resultados simulados; no utiliza Telco. Permite practicar Fisher e intervalos A/B.':task==='observacional'?'Abandono en contratos mensuales frente a contratos de uno o dos años. Comparación descriptiva sin efecto causal.':task==='clasificacion'?'Objetivo: Churn. Yes = abandona; No = permanece. División estratificada por cliente; customerID no se utiliza para predecir.':'Objetivo: MonthlyCharges. Predice el cargo mensual con servicios y características del cliente; excluye customerID, TotalCharges y Churn.';try{const d=await api(`/api/parametros?modelo=${selected.id}&tarea=${task}`);if(version!==paramsVersion)return;$('#params-summary').replaceChildren();const cells=d.variantes?[['Objetivo',d.objetivo,task==='clasificacion'?'Abandono del cliente':'Cargo mensual'],['Entrenamiento',fmt(d.entrenamiento)+' filas',d.reparto],['Prueba',fmt(d.prueba)+' filas','25% reservado; semilla '+d.semilla]]:[['Modo',labels[task],d.inferencia],['Grupos',d.grupos,''],['Datos',d.dataset,'']];for(const [a,b,c] of cells){const box=node('div',undefined,'param-cell');box.append(node('span',a),node('strong',b),node('p',c));$('#params-summary').append(box);}$('#params-code').textContent=JSON.stringify(d,null,2);if(d.avisos?.length)$('#task-note').textContent+=' '+d.avisos.join(' ');paramsReady=true;}catch(e){if(version!==paramsVersion)return;$('#params-code').textContent='No se pudo consultar la configuración.';$('#params-summary').replaceChildren(node('p','Revisa el mensaje de error.','small'));error(e);}runState();}
$('#task').addEventListener('change',loadParams);
$('#run').addEventListener('click',async()=>{if(!selected||busy||!paramsReady)return;busy=true;runState();$('#error').hidden=true;try{const result=await api('/api/run',{modelo:selected.id,tarea:$('#task').value});currentJob=result.id;$('#history').value='';$('#results').hidden=false;$('#empty-results').hidden=true;$('#results').scrollIntoView({behavior:'smooth',block:'start'});watchJob();}catch(e){busy=false;runState();error(e);}});
$('#cancel').addEventListener('click',async()=>{try{$('#cancel').disabled=true;await api('/api/cancel',{id:currentJob});watchJob();}catch(e){error(e);}finally{$('#cancel').disabled=false;}});
async function history(){const list=await api('/api/jobs');const select=$('#history');select.replaceChildren(node('option','Seleccionar una ejecución'));select.firstChild.value='';for(const j of list){const o=node('option',`${new Date(j.inicio*1000).toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit'})} · ${j.nombre} · ${labels[j.tarea]} · ${j.estado}`);o.value=j.id;select.append(o);}if(currentJob)select.value=currentJob;}
$('#history').addEventListener('change',()=>{if(!$('#history').value)return;if(busy&&$('#history').value!==currentJob){$('#history').value=currentJob;error(Error('Espera a que termine la ejecución activa para consultar otra.'));return;}currentJob=$('#history').value;watchJob();});
function caption(j,name){if(j.modelo==='10')return j.tarea==='demo'?'Demo simulada: las barras muestran proporciones e intervalos de Wilson; el segundo panel muestra B − A y su intervalo de Newcombe.':'Porcentaje de clientes que abandonaron según contrato. Las etiquetas indican abandonos y total de clientes; no demuestra causalidad.';if(name.includes('regularizacion'))return 'Ridge, Lasso y Elastic Net: perfil de un mismo cliente, variando tenure (meses) con los demás datos fijos. Las métricas de la leyenda usan todas las filas de prueba.';if(name.includes('polinomial'))return 'Una recta frente a un polinomio de grado 2. Es un perfil del modelo, no una trayectoria observada del cliente. Una curvatura pequeña puede ser correcta.';if(name.includes('reglas'))return 'Primeras tres capas del árbol. Sigue las condiciones de arriba hacia abajo; (…) indica ramas que continúan. Las categorías codificadas son indicadores 0/1.';if(j.modelo==='4')return 'El panel de selección de K utiliza solo validación cruzada del entrenamiento. Las barras representan ±1 desviación entre particiones, no intervalos de confianza. El otro panel evalúa la prueba reservada.';if(j.tarea==='clasificacion')return 'La diagonal de una matriz de confusión representa aciertos. En ROC, una curva hacia la esquina superior izquierda separa mejor las clases. Exactitud equilibrada y F1 ayudan a comparar clases de distinto tamaño.';return 'MAE y RMSE menores indican menor error en unidades monetarias del cargo mensual. En real frente a predicción, los puntos cercanos a la diagonal son mejores. Un perfil fija las otras entradas; no demuestra causalidad.';}
function showFinished(j){$('#metrics').replaceChildren();$('#chosen-params').replaceChildren();$('#plots').replaceChildren();$('#downloads').replaceChildren();if(j.estado!=='completado')return;if(j.contexto?.avisos?.length)$('#chosen-params').append(node('p',j.contexto.avisos.join(' '),'notice'));if(j.metricas){const rows=j.metricas.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,k==='modelo'?v:Number(v)])));table('#metrics',rows);const pars=j.contexto?.parametros||{};if(Object.keys(pars).length){$('#chosen-params').append(node('h4','Parámetros elegidos dentro del entrenamiento'),node('pre',JSON.stringify(pars,null,2)));}}else if(j.contexto){const c=j.contexto;if(j.tarea==='observacional'){const rows=Object.entries(c.grupos).map(([k,v])=>({grupo:c.etiquetas[k],clientes:v.filas,abandonos:v.abandonos,'abandono (%)':100*v.proporcion_abandono}));table('#metrics',rows);}else{table('#metrics',[{grupo:'A',unidades:c.n_A,'tasa (%)':100*c.tasa_A},{grupo:'B',unidades:c.n_B,'tasa (%)':100*c.tasa_B}]);$('#chosen-params').append(node('p',`Fisher bilateral: p=${Number(c.p_valor_fisher_bilateral).toPrecision(4)}. Diferencia B − A: ${(100*c.diferencia_B_menos_A).toFixed(2)} puntos porcentuales. Datos simulados.`));}}for(const file of j.archivos){if(file.nombre.endsWith('.png')){const fig=node('figure'),img=node('img');img.src=file.url;img.alt=`Gráfico de ${j.nombre}: ${file.nombre}`;const link=node('a','Abrir figura completa ↗');link.href=file.url;link.target='_blank';link.rel='noopener';fig.append(img,node('figcaption',caption(j,file.nombre)),link);$('#plots').append(fig);}else{const link=node('a',file.nombre,'button ghost');link.href=file.url;link.download=file.nombre;$('#downloads').append(link);}}}
async function watchJob(){if(poll)clearTimeout(poll);const jid=currentJob;try{const j=await api('/api/jobs/'+jid);if(jid!==currentJob)return;busy=['ejecutando','cancelando'].includes(j.estado);runState();$('#results').hidden=false;$('#empty-results').hidden=true;$('#result-title').textContent=`${j.modelo.padStart(2,'0')} · ${j.nombre} · ${labels[j.tarea]}`;const seconds=Math.max(0,Math.round((j.fin||Date.now()/1000)-j.inicio));$('#result-status').textContent=`${j.estado.charAt(0).toUpperCase()+j.estado.slice(1)} · ${seconds} s`;$('#result-status').classList.toggle('status-error',j.estado==='error');$('#log').textContent=j.log;$('#cancel').hidden=!busy;$('#progress').hidden=!busy;$('#result-note').hidden=false;$('#result-note').textContent=j.estado==='error'?(j.error||'El programa terminó con un error. Abre la consola para ver el detalle y la instrucción de instalación si falta una biblioteca.'):j.estado==='cancelado'||j.estado==='interrumpido'?'La ejecución no se completó. Puedes volver a iniciarla.':j.tarea==='demo'?'Resultados de una simulación A/B. No corresponden al dataset de Telco.':j.tarea==='observacional'?'Comparación de todos los clientes; no se entrena un predictor ni se realiza un experimento.':'Prueba reservada: 1.761 clientes (25%). Las variantes de una misma tarea usan los mismos clientes. Los hiperparámetros se eligen dentro del entrenamiento.';if(busy){$('#metrics').replaceChildren();$('#plots').replaceChildren();$('#downloads').replaceChildren();$('#chosen-params').replaceChildren();poll=setTimeout(watchJob,1200);}else{showFinished(j);await history();}}catch(e){error(e);$('#result-status').textContent='No se pudo consultar el estado. Si cerraste la terminal, vuelve a iniciar el sistema.';}}
function buildDocs(){config.documentos.forEach((d,i)=>{const box=node('article',undefined,'card doc');box.append(node('span','PDF / '+(i?'INFORME':'BITÁCORA'),'doc-icon'),node('h3',d.nombre),node('p',i?'Qué hace cada modelo con Telco, cuáles son sus parámetros principales y cómo leer sus gráficos.':'Una página con origen, alcance, parámetros de la práctica y diccionario de las 21 columnas.'));if(d.disponible){const link=node('a','Abrir PDF ↗','button primary');link.href=d.url;link.target='_blank';link.rel='noopener';const dl=node('a','Descargar','button ghost');dl.href=d.url;dl.download=d.url.split('/').pop();const actions=node('div',undefined,'actions');actions.append(link,dl);box.append(actions);}else box.append(node('p','PDF todavía no disponible.','small'));$('#documents').append(box);});}
(async()=>{try{config=await api('/api/config');buildModels();buildDocs();await Promise.all([dataset(true),history()]);if(config.activo){currentJob=config.activo;watchJob();}}catch(e){error(e);}})();
